sudo: false
language: python
cache: pip
python:
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
matrix:
  include:
    - name: Default
    - name: YAJL
      addons:
        apt:
          packages:
          - libyajl-dev
install:
  - curl -s -S --retry 3 $BASEDIR/tests/install.sh | bash -
  - pip install .[test]
  # Install ijson until > 2.4 release.
  - pip install -e git+https://github.com/ICRAR/ijson.git#egg=ijson
script:
  - curl -s -S --retry 3 $BASEDIR/tests/script.sh | bash -
  - pytest --cov ocdskit --vcr-record=none
after_success:
  coveralls
