name: CI
on: [push, pull_request]
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
        fail-fast: false
        packages:
          - ''
          - libyajl-dev
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install YAJL (Linux)
      if: matrix.packages && matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libyajl-dev
    - name: Install YAJL (macOS)
      if: matrix.packages && matrix.os == 'macos-latest'
      run: brew install yajl
    - name: Install YAJL (Windows)
      if: matrix.packages && matrix.os == 'windows-latest'
      # https://github.com/ICRAR/ijson/blob/master/.appveyor.yml
      run: |
        git clone https://github.com/lloyd/yajl
        mkdir yajl\yajl
        xcopy yajl\src\api\*.* yajl\yajl
    - run: pip install .[test]
    - name: Test
      run: |
        coverage run --append --source=ocdskit -m pytest --vcr-record=none
        pip install orjson
        coverage run --append --source=ocdskit -m pytest --vcr-record=none
        pip uninstall -y orjson
    - run: coveralls
